"""
===========================================================
QuantFormer Backend — Explain Endpoint
===========================================================

POST /api/v1/explain

Generates structured human-readable explanations combining
TFT prediction + FinBERT sentiment + Fusion insight.

Author : Team QuantFormer
Project: Multimodal Order Book & Sentiment Transformer
===========================================================
"""

from fastapi import APIRouter, Depends, HTTPException

from backend.app.api.deps import get_explain_service
from backend.app.services.explain_service import ExplainService
from backend.app.schemas.explain import ExplainRequest, ExplainResponse

router = APIRouter()


@router.post(
    "/explain",
    response_model=ExplainResponse,
    summary="AI Prediction Explainability",
    description=(
        "Explain WHY a prediction was generated by combining "
        "TFT market analysis, FinBERT sentiment, and Fusion insight "
        "into structured reasoning statements."
    ),
)
async def explain_prediction(
    request: ExplainRequest,
    service: ExplainService = Depends(get_explain_service),
) -> ExplainResponse:
    """Generate a multimodal explanation for a prediction."""

    try:
        result = service.explain(
            market_prediction=request.market_prediction,
            confidence=request.confidence,
            news_text=request.news_text,
        )
        return ExplainResponse(**result)

    except RuntimeError as e:
        raise HTTPException(
            status_code=503,
            detail={
                "error": "Model Unavailable",
                "message": str(e),
            },
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={
                "error": "Explanation Failed",
                "message": f"An error occurred: {str(e)}",
            },
        )
